# Generated by Django 4.1 on 2022-09-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_message_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='subject',
            field=models.CharField(default='Reset Password', max_length=200),
        ),
    ]
