# Generated by Django 4.1 on 2022-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_inbox_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
