# Generated by Django 4.1 on 2022-09-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_contactmail_receiver_contactreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreply',
            name='receiver',
            field=models.EmailField(default=None, max_length=255, null=True),
        ),
    ]
