# Generated by Django 4.1 on 2022-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_contactreply_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pass', models.CharField(max_length=128, verbose_name='Current Password')),
                ('new_pass', models.CharField(max_length=128, verbose_name='New Password')),
                ('confirm_pass', models.CharField(max_length=128, verbose_name='Confirm Password')),
            ],
        ),
    ]
