# Generated by Django 4.1 on 2022-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pass_reset',
            field=models.BooleanField(default=False),
        ),
    ]
