# Generated by Django 4.1 on 2022-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_country_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmail',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
