# Generated by Django 4.1 on 2022-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_contactmail_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmail',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmail',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
