# Generated by Django 4.1 on 2022-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_contactmail_email_alter_contactmail_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
