# Generated by Django 4.1 on 2022-09-03 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_profile_phone_number_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.album', verbose_name='Album')),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
