# Generated by Django 4.1 on 2022-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=b'I00\n', default='images/default.jpg', upload_to='images/gallery/'),
        ),
    ]
