# Generated by Django 4.1 on 2022-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=b'I00\n', upload_to='images/'),
        ),
    ]
