# Generated by Django 4.1 on 2022-08-17 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('fixture', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
