# Generated by Django 4.1 on 2022-08-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_fixtures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixtures',
            new_name='Fixture',
        ),
    ]
