# Generated by Django 4.1 on 2022-08-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_tag_video_vote_ratio_video_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
    ]
