# Generated by Django 4.1 on 2022-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imageBy',
            field=models.CharField(default='Funolympics Admin', max_length=200),
        ),
    ]
