# Generated by Django 4.1 on 2022-09-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
