# Generated by Django 4.1 on 2022-08-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0005_news_imageby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='meida/'),
        ),
    ]
