# Generated by Django 4.1 on 2022-09-12 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_message_inbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos_app', '0005_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideo',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ManyToManyField(blank=True, to='videos_app.category', verbose_name='Sports Category')),
                ('country', models.ManyToManyField(blank=True, to='videos_app.country', verbose_name='Participating Countries')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_live', to=settings.AUTH_USER_MODEL)),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('video_views', models.ManyToManyField(blank=True, default='admin@gmail.com', related_name='like_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
