# Generated by Django 4.1 on 2022-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0006_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
