# Generated by Django 4.1 on 2022-08-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0007_standing_alter_video_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='category',
        ),
    ]
