# Generated by Django 4.1 on 2022-08-18 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos_app', '0008_rename_tag_category_rename_tags_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
