# Generated by Django 4.1 on 2022-08-20 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0009_video_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(blank=True, to='videos_app.category', verbose_name='Sports Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.ManyToManyField(blank=True, to='videos_app.country', verbose_name='Participating Countries'),
        ),
    ]
