# Generated by Django 4.1 on 2022-08-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0010_country_alter_video_category_video_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='videos_app.video')),
            ],
        ),
    ]
