# Generated by Django 4.1 on 2022-08-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_country'),
        ('videos_app', '0014_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
