# Generated by Django 4.1 on 2022-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0015_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
