# Generated by Django 4.1 on 2022-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0018_news_author_news_photo_caption_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, default='images/profile_pics/default.jpg', null=True, upload_to='images/players/'),
        ),
    ]
