# Generated by Django 4.1 on 2022-08-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0018_review_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
    ]
