# Generated by Django 4.1 on 2022-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0019_players_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
