# Generated by Django 4.1 on 2022-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0020_rename_players_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='thumbnail',
            field=models.ImageField(default='media/images/background/bg.png', upload_to='images/fixtures/'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(),
        ),
    ]
