# Generated by Django 4.1 on 2022-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0021_fixture_thumbnail_alter_fixture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(verbose_name='Game Date'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='thumbnail',
            field=models.ImageField(blank=True, default='media/images/background/bg.png', null=True, upload_to='images/fixtures/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='country',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
