# Generated by Django 4.1 on 2022-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0022_alter_fixture_date_alter_fixture_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Game Date'),
        ),
    ]
