# Generated by Django 4.1 on 2022-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0023_alter_fixture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(verbose_name='Game Date'),
        ),
    ]
