# Generated by Django 4.1 on 2022-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0024_alter_fixture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, to='videos_app.category', verbose_name='News Category'),
        ),
    ]
