# Generated by Django 4.1 on 2022-09-24 06:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0025_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Participating'),
        ),
    ]
