# Generated by Django 4.1 on 2022-09-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0027_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(to='videos_app.category', verbose_name='Sports Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='country',
            field=models.ManyToManyField(blank=b'I00\n', to='videos_app.country', verbose_name='Participating Countries'),
        ),
    ]
