# Generated by Django 4.1 on 2022-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0028_alter_video_category_alter_video_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='country',
            field=models.ManyToManyField(to='videos_app.country', verbose_name='Participating Countries'),
        ),
    ]
