# Generated by Django 4.1 on 2022-09-26 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_contactmail_full_name'),
        ('videos_app', '0029_alter_video_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveComments',
            fields=[
                ('comment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_app.livevideo')),
            ],
        ),
    ]
