# Generated by Django 4.1 on 2022-09-28 06:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0030_livecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livevideo',
            name='url',
            field=embed_video.fields.EmbedVideoField(verbose_name='Live URL'),
        ),
    ]
